var sv_iSlider=function(){
	var mainLis,cur,navLis,ani,ti,ul,ct,ctr,del,dur,st,stf,old;
	return{
		init:function(opts){
			el=document.getElementById(opts.id);
			if(!el){return;}
			ele=document.getElementById(opts.id2);
			if(!ele){return;}
			ele.onclick=sv_iSlider.click;
			var main=el.getElementsByTagName('div')[0];
			mainLis=main.getElementsByTagName('li');
			for(var i=0;i<mainLis.length-2;i++){
				mainLis[i].style.display="none";
				mainLis[i].style.zIndex=1;
			}
			mainLis[mainLis.length-1].style.display="block";
			mainLis[mainLis.length-1].style.zIndex=2;			
			var nav=el.getElementsByTagName('div')[1];
			navLis=nav.getElementsByTagName('li');
			old=navLis.length-1;
			cur=navLis.length-1;			
			ul = nav.getElementsByTagName('ul')[0];
			ul.style.position="relative";
			del=opts.delay;
			dur=opts.duration/opts.steps;
			ani=false;
			st=navLis[0].offsetHeight/opts.steps;
			stf=100/opts.steps;
			sv_iSlider.cloneNode();
			ti=setTimeout(sv_iSlider.trans,del);
		},
		cloneNode:function(){		 
			li =document.createElement("li");
			li.innerHTML=navLis[navLis.length-1].innerHTML;
			ul.removeChild(navLis[navLis.length-1]);
			ul.insertBefore(li,navLis[0]);
			ct=-((navLis.length-3)*li.offsetHeight);
			ul.style.top=ct+"px";		
		},
		click:function(){
			if(!ani){
				clearTimeout(ti);ti=null;
				sv_iSlider.trans();
			}
		},
		trans:function(){	
			if(!ani){
				ctr=100;
				old=cur;
				if((cur-1)<0){
					cur=navLis.length-1;
				}
				else{
					cur-=1;
				}
				mOld=mainLis[old].style;
				mCur=mainLis[cur].style;
				mOld.display="block";
				mOld.zIndex=2;	
				mOld.opacity=ctr/100;
				mOld.filter='alpha(opacity='+ctr+')';		
				mCur.display="block";
				mCur.zIndex=1;
				mCur.opacity=ctr/100;
				mCur.filter='alpha(opacity='+ctr+')';		
				sv_iSlider.move();
			}
		},
		move:function(){	
			ani=true;
			mOld=mainLis[old].style;
			if(ctr>0){
				ctr-=stf;
				mOld.opacity=ctr/100;
				mOld.filter='alpha(opacity='+ctr+')';			
			}
			else{
				mOld.display="none";
				mOld.zIndex=1;
				mOld.opacity=ctr/100;
				mOld.filter='alpha(opacity='+ctr+')';			
			}
			if(ct<-((navLis.length-4)*li.offsetHeight)){
				ct+=st;
				ul.style.top=ct+"px";
			}
			else{
				ct=-((navLis.length-4)*li.offsetHeight);
				ul.style.top=ct+"px";
				sv_iSlider.cloneNode();	
				ti=setTimeout(sv_iSlider.trans,del);
				ani=false;return;
			}	
			ti=setTimeout(sv_iSlider.move,dur);
		}
	}
}();